services:
  postgres:
    build:
      context: .
      dockerfile: build/postgres/Dockerfile
    environment:
      POSTGRES_USER: osef
      POSTGRES_PASSWORD: osef
      POSTGRES_DB: osef
    ports:
      - "127.0.0.1:5432:5432"
    shm_size: 512mb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  rox_data:
