[package]
name    = "seeder"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "seeder"
path = "src/main.rs"

[dependencies]
tokio              = { workspace = true }
serde              = { workspace = true }
dotenvy            = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
ratatui            = { workspace = true }
crossterm          = { workspace = true }
anyhow             = { workspace = true }
chrono             = { workspace = true }
bridge             = { path = "../../crates/bridge" }
db                 = { path = "../../crates/db" }
