[package]
name = "server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
tokio              = { workspace = true }
axum               = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
dotenvy            = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
moka               = { version = "0.12", features = ["future"] }
base64             = "0.22"
metron-rs          = { path = "../../crates/metron" }
minacalc-rs        = "515"
rox-formats        = { path = "../../crates/roe/crates/formats", features = ["std"] }
rox-analysis       = { path = "../../crates/roe/crates/analysis" }
rox                = { path = "../../crates/roe/crates/rox" }

[dev-dependencies]
tempfile = "3"
